language: objective-c

os:
  - osx
osx_image: xcode10.1

before_install:
  - pod install

script:
  - xcodebuild -workspace Buya.xcworkspace -scheme BuyaTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.1' test | xcpretty
